# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration





client_id = "e3c6df0e7669a438f16b27083aa321d0"
name = "Carousel Slider"
handle = "slide-extension"
application_url = "https://carouselslider-sandy.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "saastester.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://carouselslider-sandy.vercel.app/auth/callback",
  "https://carouselslider-sandy.vercel.app/auth/shopify/callback",
  "https://carouselslider-sandy.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/privacy"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]



[[extensions]]
  type = "theme_app_extension"
  name = "Slide Theme App Extension"
  handle = "slide-extension"



[pos]
embedded = false
